spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=grocery_manager
    username: postgres
    password: mypass

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true